# Configuration file path of logging
log_cfg: logging.yml

workers_num: 8
# Local ports listened by each service
port:
  master: 11111
  trainer: 11112
  worker: 11113
# Network address when accessing. m, t, w0 correspond to master, trainer, worker0 respectively.
net:
  # # for real local network
  # m->t: '192.168.0.27:11112'
  # m->w0: '192.168.0.114:11113'
  # m->w1: '192.168.0.115:11114'
  # # m->w2: '192.168.0.115:11115'
  # w0->w1: '192.168.0.115:11114'
  # # w1->w2: '192.168.0.115:11115' 

  # for docker network
  m->t: 174.28.0.2:11112
  m->w0: 174.28.0.3:11113
  m->w1: 174.28.0.4:11113
  m->w2: 174.28.0.5:11113
  m->w3: 174.28.0.6:11113
  m->w4: 174.28.0.7:11113
  m->w5: 174.28.0.8:11113
  m->w6: 174.28.0.9:11113
  m->w7: 174.28.0.10:11113
  w0->w1: 174.28.0.4:11113
  w1->w2: 174.28.0.5:11113
  w2->w3: 174.28.0.6:11113
  w3->w4: 174.28.0.7:11113
  w4->w5: 174.28.0.8:11113
  w5->w6: 174.28.0.9:11113
  w6->w7: 174.28.0.10:11113

# DNN load function, use this to choose dnn
# dnn_loader: !!python/name:dnn_models.any_dnn_split.prepare_alexnet
dnn_loader: !!python/name:dnn_models.any_dnn_split.prepare_vgg16
# dnn_loader: !!python/name:dnn_models.any_dnn_split.prepare_resnet18
# dnn_loader: !!python/name:dnn_models.any_dnn_split.prepare_resnet50
# dnn_loader: !!python/name:dnn_models.any_dnn_split.prepare_googlenet
# dnn_loader: !!python/name:dnn_models.any_dnn_split.prepare_regnet
# dnn_loader: !!python/name:dnn_models.any_dnn_split.prepare_inception_v3
# Path of the input video file
video_path: media/parking.mp4
# Adjust the input frame to [nrow, ncol], which is a tuple of two int. None indicates don't resize.
frame_size: !!python/tuple [480, 720]
# "itg" or "dif". This option generates two corresponding options: executor_type and job_type
mode: dif
# mode: itg
# Whether check the correctness of result
check: !!bool false

# Configuration of master
master:
  ifr_num: 11  # Total frame to be processed
  pd_num: 0  # How many frames are pending at the same time, 0 means unlimited
  itv_time: 0  # How long to wait after issuing an IFR, for debugging only. Normally it should be 0
  # len(bandwidth) must be equal to len(worker).
  # bandwidth[w] = bandwidth(MB) between w-1 and w. bandwidth[0] refers to master and worker0.
  bandwidth:
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  - 10
  # bandwidth: [3, 3, 3]
  scheduler: !!python/name:schedulers.my_scheduler.MyScheduler
  # scheduler: !!python/name:schedulers.lb_scheduler.LBScheduler
  LBScheduler:
  MyScheduler:
    gp_size: 10  # The number of frames a group contains. A group of frames will use the same scheduling policy
    # gp_size: 3 # for real local network, it should be 3; for docker network, it should be 10
  OSCScheduler:
    side: edge  # edge/cloud
  NSCScheduler:
# Configuration of worker
worker:
  prof_niter: 5
# Configuration of trainer
trainer:
  frame_num: 400