# Settings and configurations that are common for all containers
x-paoding-common: &paoding-common
  image: pao-ding:1.0
  
services:
  paoding-master:
    <<: *paoding-common
    command: python3 main.py master
    networks:
      - paoding-network
    depends_on:
      paoding-trainer:
        condition: service_healthy
      paoding-worker0:
        condition: service_healthy
      paoding-worker1:
        condition: service_healthy
    # volumes:
    #   - data1-1:/data1
    #   - data1-2:/data2

  paoding-trainer:
    <<: *paoding-common
    command: python3 main.py trainer
    networks:
      - paoding-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 10m
      retries: 60
    # volumes:
    #   - data2-1:/data1
    #   - data2-2:/data2

  paoding-worker0:
    <<: *paoding-common
    command: python3 main.py worker -i 0
    networks:
      - paoding-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 10m
      retries: 60
    # volumes:
    #   - data2-1:/data1
    #   - data2-2:/data2

  paoding-worker1:
    <<: *paoding-common
    command: python3 main.py worker -i 1
    networks:
      - paoding-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 10m
      retries: 60
    # volumes:
    #   - data2-1:/data1
    #   - data2-2:/data2

# volumes:
#   data1-1:
#   data1-2:
#   data2-1:
#   data2-2:

networks:
  paoding-network: