# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/msg.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrpc/msg.proto\x12\x03msg\"(\n\x08\x41rr2dMsg\x12\x0e\n\x06sparse\x18\x01 \x02(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\")\n\x08\x41rr3dMsg\x12\x1d\n\x06\x61rr2ds\x18\x01 \x03(\x0b\x32\r.msg.Arr2dMsg\"\x95\x01\n\x06JobMsg\x12\x10\n\x08\x65xec_ids\x18\x01 \x03(\x05\x12\x0f\n\x07out_ids\x18\x02 \x03(\x05\x12)\n\x07id2data\x18\x03 \x03(\x0b\x32\x18.msg.JobMsg.Id2dataEntry\x1a=\n\x0cId2dataEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.msg.Arr3dMsg:\x02\x38\x01\";\n\x08WkJobMsg\x12\x11\n\tworker_id\x18\x01 \x02(\x05\x12\x1c\n\x07job_msg\x18\x02 \x02(\x0b\x32\x0b.msg.JobMsg\"4\n\x06IFRMsg\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x1e\n\x07wk_jobs\x18\x02 \x03(\x0b\x32\r.msg.WkJobMsg\"@\n\x08StageMsg\x12\x0e\n\x06ifr_id\x18\x01 \x02(\x05\x12\x11\n\tworker_id\x18\x02 \x02(\x05\x12\x11\n\tsub_stage\x18\x03 \x02(\x05\"\x05\n\x03Rsp\"\x05\n\x03Req\"\x1d\n\x0cLayerCostMsg\x12\r\n\x05\x63osts\x18\x01 \x02(\x0c\"\x1d\n\x0c\x42\x61ndwidthMsg\x12\r\n\x05infos\x18\x01 \x02(\x0c\"9\n\tFinishMsg\x12\x0e\n\x06ifr_id\x18\x01 \x02(\x05\x12\x1c\n\x05\x61rr3d\x18\x02 \x01(\x0b\x32\r.msg.Arr3dMsg\"\x1b\n\tNZPredMsg\x12\x0e\n\x06nzpred\x18\x01 \x02(\x0c\x32\xe3\x01\n\x06Worker\x12 \n\x07new_ifr\x12\x0b.msg.IFRMsg\x1a\x08.msg.Rsp\x12)\n\nlayer_cost\x12\x08.msg.Req\x1a\x11.msg.LayerCostMsg\x12/\n\x11report_finish_rev\x12\x08.msg.Req\x1a\x0e.msg.FinishMsg0\x01\x12-\n\x10\x66inish_stage_rev\x12\x08.msg.Req\x1a\r.msg.StageMsg0\x01\x12,\n\rget_bandwidth\x12\x08.msg.Req\x1a\x11.msg.BandwidthMsg21\n\x07Trainer\x12&\n\nget_nzpred\x12\x08.msg.Req\x1a\x0e.msg.NZPredMsg')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc.msg_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_JOBMSG_ID2DATAENTRY']._options = None
  _globals['_JOBMSG_ID2DATAENTRY']._serialized_options = b'8\001'
  _globals['_ARR2DMSG']._serialized_start=22
  _globals['_ARR2DMSG']._serialized_end=62
  _globals['_ARR3DMSG']._serialized_start=64
  _globals['_ARR3DMSG']._serialized_end=105
  _globals['_JOBMSG']._serialized_start=108
  _globals['_JOBMSG']._serialized_end=257
  _globals['_JOBMSG_ID2DATAENTRY']._serialized_start=196
  _globals['_JOBMSG_ID2DATAENTRY']._serialized_end=257
  _globals['_WKJOBMSG']._serialized_start=259
  _globals['_WKJOBMSG']._serialized_end=318
  _globals['_IFRMSG']._serialized_start=320
  _globals['_IFRMSG']._serialized_end=372
  _globals['_STAGEMSG']._serialized_start=374
  _globals['_STAGEMSG']._serialized_end=438
  _globals['_RSP']._serialized_start=440
  _globals['_RSP']._serialized_end=445
  _globals['_REQ']._serialized_start=447
  _globals['_REQ']._serialized_end=452
  _globals['_LAYERCOSTMSG']._serialized_start=454
  _globals['_LAYERCOSTMSG']._serialized_end=483
  _globals['_BANDWIDTHMSG']._serialized_start=485
  _globals['_BANDWIDTHMSG']._serialized_end=514
  _globals['_FINISHMSG']._serialized_start=516
  _globals['_FINISHMSG']._serialized_end=573
  _globals['_NZPREDMSG']._serialized_start=575
  _globals['_NZPREDMSG']._serialized_end=602
  _globals['_WORKER']._serialized_start=605
  _globals['_WORKER']._serialized_end=832
  _globals['_TRAINER']._serialized_start=834
  _globals['_TRAINER']._serialized_end=883
# @@protoc_insertion_point(module_scope)
