# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rpc import msg_pb2 as rpc_dot_msg__pb2


class WorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.new_ifr = channel.unary_unary(
                '/msg.Worker/new_ifr',
                request_serializer=rpc_dot_msg__pb2.IFRMsg.SerializeToString,
                response_deserializer=rpc_dot_msg__pb2.Rsp.FromString,
                )
        self.layer_cost = channel.unary_unary(
                '/msg.Worker/layer_cost',
                request_serializer=rpc_dot_msg__pb2.Req.SerializeToString,
                response_deserializer=rpc_dot_msg__pb2.LayerCostMsg.FromString,
                )
        self.report_finish_rev = channel.unary_stream(
                '/msg.Worker/report_finish_rev',
                request_serializer=rpc_dot_msg__pb2.Req.SerializeToString,
                response_deserializer=rpc_dot_msg__pb2.FinishMsg.FromString,
                )
        self.finish_stage_rev = channel.unary_stream(
                '/msg.Worker/finish_stage_rev',
                request_serializer=rpc_dot_msg__pb2.Req.SerializeToString,
                response_deserializer=rpc_dot_msg__pb2.StageMsg.FromString,
                )


class WorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def new_ifr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def layer_cost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def report_finish_rev(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def finish_stage_rev(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'new_ifr': grpc.unary_unary_rpc_method_handler(
                    servicer.new_ifr,
                    request_deserializer=rpc_dot_msg__pb2.IFRMsg.FromString,
                    response_serializer=rpc_dot_msg__pb2.Rsp.SerializeToString,
            ),
            'layer_cost': grpc.unary_unary_rpc_method_handler(
                    servicer.layer_cost,
                    request_deserializer=rpc_dot_msg__pb2.Req.FromString,
                    response_serializer=rpc_dot_msg__pb2.LayerCostMsg.SerializeToString,
            ),
            'report_finish_rev': grpc.unary_stream_rpc_method_handler(
                    servicer.report_finish_rev,
                    request_deserializer=rpc_dot_msg__pb2.Req.FromString,
                    response_serializer=rpc_dot_msg__pb2.FinishMsg.SerializeToString,
            ),
            'finish_stage_rev': grpc.unary_stream_rpc_method_handler(
                    servicer.finish_stage_rev,
                    request_deserializer=rpc_dot_msg__pb2.Req.FromString,
                    response_serializer=rpc_dot_msg__pb2.StageMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'msg.Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Worker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def new_ifr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/msg.Worker/new_ifr',
            rpc_dot_msg__pb2.IFRMsg.SerializeToString,
            rpc_dot_msg__pb2.Rsp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def layer_cost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/msg.Worker/layer_cost',
            rpc_dot_msg__pb2.Req.SerializeToString,
            rpc_dot_msg__pb2.LayerCostMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def report_finish_rev(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/msg.Worker/report_finish_rev',
            rpc_dot_msg__pb2.Req.SerializeToString,
            rpc_dot_msg__pb2.FinishMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def finish_stage_rev(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/msg.Worker/finish_stage_rev',
            rpc_dot_msg__pb2.Req.SerializeToString,
            rpc_dot_msg__pb2.StageMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class TrainerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_nzpred = channel.unary_unary(
                '/msg.Trainer/get_nzpred',
                request_serializer=rpc_dot_msg__pb2.Req.SerializeToString,
                response_deserializer=rpc_dot_msg__pb2.NZPredMsg.FromString,
                )


class TrainerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_nzpred(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_nzpred': grpc.unary_unary_rpc_method_handler(
                    servicer.get_nzpred,
                    request_deserializer=rpc_dot_msg__pb2.Req.FromString,
                    response_serializer=rpc_dot_msg__pb2.NZPredMsg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'msg.Trainer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Trainer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_nzpred(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/msg.Trainer/get_nzpred',
            rpc_dot_msg__pb2.Req.SerializeToString,
            rpc_dot_msg__pb2.NZPredMsg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
